import type { Locale } from "./site-copy";

export type ResourceKind = "privacy" | "terms" | "support" | "delete-account";

export const localeConfig: Record<Locale, { label: string; lang: string; prefix: string }> = {
  en: { label: "EN", lang: "en", prefix: "" },
  uk: { label: "UA", lang: "uk", prefix: "/ua" },
  pl: { label: "PL", lang: "pl", prefix: "/pl" },
  ru: { label: "RU", lang: "ru", prefix: "/ru" },
};

export const localeOrder: Locale[] = ["en", "uk", "pl", "ru"];

export function localizedPath(locale: Locale, resource?: ResourceKind) {
  const prefix = localeConfig[locale].prefix;
  return resource ? `${prefix}/${resource}` : prefix || "/";
}

export const resourceCopy = {
  en: {
    back: "Back to Eliyo",
    canonicalNotice: "The English version is the canonical legal version.",
    footer: { privacy: "Privacy", terms: "Terms", support: "Support", deleteAccount: "Delete account", cookieSettings: "Cookie settings", copyright: "© 2026 Eliyo" },
    cookies: {
      label: "Cookie consent",
      title: "We use cookies",
      text: "We use Microsoft Clarity only with your permission to understand how the website is used.",
      accept: "Accept",
      decline: "Decline",
      close: "Close cookie settings",
    },
    support: {
      title: "Support",
      description: "Tell us what you need help with. Eliyo support is handled directly by email.",
      emailLabel: "Email Eliyo support",
      response: "Include the email linked to your Eliyo account when the request concerns your account or subscription.",
      categoriesTitle: "What can we help with?",
      categories: [
        ["Account or login", "Problems signing in, verification or account access."],
        ["Subscription", "Eliyo+ access, purchase status, cancellation or refund questions."],
        ["Bug or problem", "Something in Eliyo is not working as expected."],
        ["Privacy or data request", "Access, export, correction or deletion of your personal data."],
        ["Other support", "Anything else related to Eliyo."],
      ],
      subject: "Eliyo support request",
    },
    deleteAccount: {
      title: "Delete your Eliyo account",
      description: "You can request permanent deletion even if Eliyo is no longer installed on your device.",
      stepsTitle: "How to request deletion",
      steps: [
        "Email eliyo.app@gmail.com from the address linked to your Eliyo account.",
        "Use the subject “Eliyo account deletion request”.",
        "We may ask for limited information to verify that you own the account before deletion begins.",
        "After verification, we will process the request and confirm when it is complete.",
      ],
      button: "Request account deletion",
      subject: "Eliyo account deletion request",
      body: "Hello,\n\nI want to permanently delete my Eliyo account and associated data.\n\nAccount email:\n\nThank you.",
      deletedTitle: "What is deleted",
      deleted: [
        "Your Eliyo profile and account data.",
        "Vehicles, mileage, maintenance, expenses and history.",
        "Documents, images and other stored vehicle files.",
        "Eliyo Assistant conversations and locally indexed AI attachments associated with the account.",
        "Eliyo subscription entitlement records held for the account, where supported by the provider.",
      ],
      retainedTitle: "What may remain",
      retained: "Limited records may remain where required for legal, tax, security, fraud-prevention or dispute-resolution purposes. Deleted data may also remain temporarily in provider backups until those backups are rotated.",
      subscriptionTitle: "Your subscription is separate",
      subscription: "Deleting your Eliyo account does not automatically cancel an Apple App Store or Google Play subscription. Cancel it first through Apple Settings > your Apple ID > Subscriptions, or Google Play > Payments & subscriptions > Subscriptions.",
      inApp: "If you can still sign in, you can also delete the account directly in the Eliyo app.",
    },
  },
  uk: {
    back: "Повернутися до Eliyo",
    canonicalNotice: "Англійська версія є основною юридичною версією.",
    footer: { privacy: "Конфіденційність", terms: "Умови", support: "Підтримка", deleteAccount: "Видалити акаунт", cookieSettings: "Налаштування cookies", copyright: "© 2026 Eliyo" },
    cookies: {
      label: "Згода на cookies",
      title: "Ми використовуємо cookies",
      text: "Ми використовуємо Microsoft Clarity лише з вашого дозволу, щоб розуміти, як використовується сайт.",
      accept: "Прийняти",
      decline: "Відхилити",
      close: "Закрити налаштування cookies",
    },
    support: {
      title: "Підтримка",
      description: "Розкажіть, із чим вам потрібна допомога. Підтримка Eliyo працює безпосередньо через email.",
      emailLabel: "Написати в підтримку Eliyo",
      response: "Якщо запит стосується акаунта або підписки, вкажіть email, пов’язаний із вашим акаунтом Eliyo.",
      categoriesTitle: "Із чим ми можемо допомогти?",
      categories: [
        ["Акаунт або вхід", "Проблеми зі входом, підтвердженням або доступом до акаунта."],
        ["Підписка", "Доступ до Eliyo+, статус покупки, скасування або повернення коштів."],
        ["Помилка або проблема", "Щось в Eliyo працює не так, як очікувалося."],
        ["Конфіденційність або дані", "Доступ, експорт, виправлення або видалення персональних даних."],
        ["Інша допомога", "Будь-які інші питання щодо Eliyo."],
      ],
      subject: "Запит до підтримки Eliyo",
    },
    deleteAccount: {
      title: "Видалення акаунта Eliyo",
      description: "Ви можете подати запит на остаточне видалення, навіть якщо Eliyo більше не встановлено на вашому пристрої.",
      stepsTitle: "Як подати запит",
      steps: [
        "Напишіть на eliyo.app@gmail.com з адреси, пов’язаної з вашим акаунтом Eliyo.",
        "Використайте тему «Запит на видалення акаунта Eliyo».",
        "Перед початком видалення ми можемо попросити обмежену інформацію, щоб підтвердити, що акаунт належить вам.",
        "Після перевірки ми опрацюємо запит і підтвердимо завершення.",
      ],
      button: "Запросити видалення акаунта",
      subject: "Запит на видалення акаунта Eliyo",
      body: "Вітаю,\n\nЯ хочу остаточно видалити свій акаунт Eliyo та пов’язані з ним дані.\n\nEmail акаунта:\n\nДякую.",
      deletedTitle: "Що буде видалено",
      deleted: [
        "Профіль і дані акаунта Eliyo.",
        "Автомобілі, пробіг, обслуговування, витрати та історія.",
        "Документи, зображення та інші збережені файли автомобіля.",
        "Розмови з Eliyo Assistant і локально індексовані AI-вкладення, пов’язані з акаунтом.",
        "Записи про права доступу за підпискою Eliyo, якщо це підтримує постачальник.",
      ],
      retainedTitle: "Що може залишитися",
      retained: "Обмежені записи можуть зберігатися, якщо це необхідно для юридичних, податкових, безпекових цілей, запобігання шахрайству або вирішення спорів. Видалені дані також можуть тимчасово залишатися в резервних копіях постачальників до їх планового оновлення.",
      subscriptionTitle: "Підписка скасовується окремо",
      subscription: "Видалення акаунта Eliyo не скасовує автоматично підписку в Apple App Store або Google Play. Спочатку скасуйте її через Налаштування Apple > ваш Apple ID > Підписки або Google Play > Платежі та підписки > Підписки.",
      inApp: "Якщо ви ще можете увійти, акаунт також можна видалити безпосередньо в застосунку Eliyo.",
    },
  },
  pl: {
    back: "Wróć do Eliyo",
    canonicalNotice: "Wersja angielska jest nadrzędną wersją prawną.",
    footer: { privacy: "Prywatność", terms: "Warunki", support: "Pomoc", deleteAccount: "Usuń konto", cookieSettings: "Ustawienia cookies", copyright: "© 2026 Eliyo" },
    cookies: {
      label: "Zgoda na cookies",
      title: "Używamy cookies",
      text: "Korzystamy z Microsoft Clarity wyłącznie za Twoją zgodą, aby rozumieć sposób używania witryny.",
      accept: "Akceptuję",
      decline: "Odrzuć",
      close: "Zamknij ustawienia cookies",
    },
    support: {
      title: "Pomoc",
      description: "Napisz, w czym potrzebujesz pomocy. Pomoc Eliyo jest obsługiwana bezpośrednio przez email.",
      emailLabel: "Napisz do pomocy Eliyo",
      response: "Jeśli sprawa dotyczy konta lub subskrypcji, podaj adres email powiązany z kontem Eliyo.",
      categoriesTitle: "W czym możemy pomóc?",
      categories: [
        ["Konto lub logowanie", "Problemy z logowaniem, weryfikacją lub dostępem do konta."],
        ["Subskrypcja", "Dostęp do Eliyo+, status zakupu, anulowanie lub pytania o zwrot."],
        ["Błąd lub problem", "Coś w Eliyo nie działa zgodnie z oczekiwaniami."],
        ["Prywatność lub dane", "Dostęp, eksport, poprawienie lub usunięcie danych osobowych."],
        ["Inna pomoc", "Wszystkie pozostałe sprawy dotyczące Eliyo."],
      ],
      subject: "Prośba o pomoc Eliyo",
    },
    deleteAccount: {
      title: "Usuń konto Eliyo",
      description: "Możesz poprosić o trwałe usunięcie konta, nawet jeśli aplikacja Eliyo nie jest już zainstalowana na urządzeniu.",
      stepsTitle: "Jak poprosić o usunięcie",
      steps: [
        "Napisz na eliyo.app@gmail.com z adresu powiązanego z kontem Eliyo.",
        "Użyj tematu „Prośba o usunięcie konta Eliyo”.",
        "Przed rozpoczęciem usuwania możemy poprosić o ograniczone informacje potwierdzające, że konto należy do Ciebie.",
        "Po weryfikacji zrealizujemy prośbę i potwierdzimy jej zakończenie.",
      ],
      button: "Poproś o usunięcie konta",
      subject: "Prośba o usunięcie konta Eliyo",
      body: "Dzień dobry,\n\nChcę trwale usunąć moje konto Eliyo i powiązane z nim dane.\n\nEmail konta:\n\nDziękuję.",
      deletedTitle: "Co zostanie usunięte",
      deleted: [
        "Profil i dane konta Eliyo.",
        "Pojazdy, przebieg, serwis, wydatki i historia.",
        "Dokumenty, obrazy i inne zapisane pliki pojazdu.",
        "Rozmowy z Eliyo Assistant i lokalnie indeksowane załączniki AI powiązane z kontem.",
        "Rekordy uprawnień subskrypcyjnych Eliyo przypisane do konta, jeśli dostawca to obsługuje.",
      ],
      retainedTitle: "Co może pozostać",
      retained: "Ograniczone rekordy mogą pozostać, jeśli wymagają tego obowiązki prawne lub podatkowe, bezpieczeństwo, zapobieganie oszustwom albo rozstrzyganie sporów. Usunięte dane mogą też tymczasowo pozostać w kopiach zapasowych dostawców do czasu ich rotacji.",
      subscriptionTitle: "Subskrypcję anuluje się osobno",
      subscription: "Usunięcie konta Eliyo nie anuluje automatycznie subskrypcji Apple App Store ani Google Play. Najpierw anuluj ją w Ustawieniach Apple > Twój Apple ID > Subskrypcje albo Google Play > Płatności i subskrypcje > Subskrypcje.",
      inApp: "Jeśli nadal możesz się zalogować, konto możesz również usunąć bezpośrednio w aplikacji Eliyo.",
    },
  },
  ru: {
    back: "Вернуться в Eliyo",
    canonicalNotice: "Английская версия является основной юридической версией.",
    footer: { privacy: "Конфиденциальность", terms: "Условия", support: "Поддержка", deleteAccount: "Удалить аккаунт", cookieSettings: "Настройки cookies", copyright: "© 2026 Eliyo" },
    cookies: {
      label: "Согласие на cookies",
      title: "Мы используем cookies",
      text: "Мы используем Microsoft Clarity только с вашего разрешения, чтобы понимать, как используется сайт.",
      accept: "Принять",
      decline: "Отклонить",
      close: "Закрыть настройки cookies",
    },
    support: {
      title: "Поддержка",
      description: "Расскажите, с чем вам нужна помощь. Поддержка Eliyo работает напрямую через email.",
      emailLabel: "Написать в поддержку Eliyo",
      response: "Если вопрос касается аккаунта или подписки, укажите email, связанный с вашим аккаунтом Eliyo.",
      categoriesTitle: "С чем мы можем помочь?",
      categories: [
        ["Аккаунт или вход", "Проблемы со входом, подтверждением или доступом к аккаунту."],
        ["Подписка", "Доступ к Eliyo+, статус покупки, отмена или возврат средств."],
        ["Ошибка или проблема", "Что-то в Eliyo работает не так, как ожидалось."],
        ["Конфиденциальность или данные", "Доступ, экспорт, исправление или удаление персональных данных."],
        ["Другая помощь", "Любые другие вопросы об Eliyo."],
      ],
      subject: "Запрос в поддержку Eliyo",
    },
    deleteAccount: {
      title: "Удаление аккаунта Eliyo",
      description: "Вы можете запросить окончательное удаление, даже если Eliyo больше не установлено на вашем устройстве.",
      stepsTitle: "Как подать запрос",
      steps: [
        "Напишите на eliyo.app@gmail.com с адреса, связанного с вашим аккаунтом Eliyo.",
        "Используйте тему «Запрос на удаление аккаунта Eliyo».",
        "До начала удаления мы можем запросить ограниченную информацию, чтобы подтвердить, что аккаунт принадлежит вам.",
        "После проверки мы обработаем запрос и подтвердим завершение.",
      ],
      button: "Запросить удаление аккаунта",
      subject: "Запрос на удаление аккаунта Eliyo",
      body: "Здравствуйте,\n\nЯ хочу окончательно удалить мой аккаунт Eliyo и связанные с ним данные.\n\nEmail аккаунта:\n\nСпасибо.",
      deletedTitle: "Что будет удалено",
      deleted: [
        "Профиль и данные аккаунта Eliyo.",
        "Автомобили, пробег, обслуживание, расходы и история.",
        "Документы, изображения и другие сохранённые файлы автомобиля.",
        "Разговоры с Eliyo Assistant и локально индексированные AI-вложения, связанные с аккаунтом.",
        "Записи о правах доступа по подписке Eliyo, если это поддерживается провайдером.",
      ],
      retainedTitle: "Что может сохраниться",
      retained: "Ограниченные записи могут храниться, если это необходимо для юридических, налоговых целей, безопасности, предотвращения мошенничества или разрешения споров. Удалённые данные также могут временно оставаться в резервных копиях провайдеров до их планового обновления.",
      subscriptionTitle: "Подписка отменяется отдельно",
      subscription: "Удаление аккаунта Eliyo не отменяет автоматически подписку Apple App Store или Google Play. Сначала отмените её через Настройки Apple > ваш Apple ID > Подписки либо Google Play > Платежи и подписки > Подписки.",
      inApp: "Если вы ещё можете войти, аккаунт также можно удалить непосредственно в приложении Eliyo.",
    },
  },
} as const;
